<div class="terms-condition text-align-justify p-3 fs-0"  style="color:#000;list-style: none;">
   <p class="text-align"><strong><span style="">Portal Educonexiones</span></strong></p>
   <p class="text-align"><strong><span style="">Términos y Condiciones.</span></strong></p>
   <p style=""><strong><span>Educonexiones</span></strong><span>, le da la bienvenida.</span></p>
   <p><span>A continuación, presentamos los términos y condiciones que como usuario del portal <strong>
   <strong>Educonexiones </strong>
   </strong> debe conocer y aceptar para acceder a los servicios y contenidos que tiene vinculados. </span></p>
   <p>
      <strong> <span>ANOTACIÓN: </span> </strong>
      <span>se entiende como usuario de <strong>Educonexiones,</strong> toda persona que ingrese a la dirección web  <a href="https://educonexiones.com/"> <strong class="text-underline">https://educonexiones.com</strong></a>  y a las páginas asociadas a esta url, para usar los servicios y contenidos que ofrece.</span>
   </p>
   <p><strong><span>IMPORTANTE</span></strong><span>: al aceptar los términos y condiciones que aquí se exponen, usted se reconoce como usuario de <strong> Educonexiones</strong>, manifiesta comprender a cabalidad el sentido y alcance de los mismos, y manifiesta de manera expresa estar de acuerdo con estos.</span></p>
   <p><strong><span>RECOMENDACIÓN</span></strong><span>: cada que ingrese a <strong> Educonexiones</strong>, consulte de nuevo los términos y condiciones dispuesto en la plataforma, pues estos pueden ser modificados y actualizados en cualquier momento sin previo aviso.</span></p>
   <li><strong>1. <span>Alcance del servicio y requerimientos técnicos</span></strong></li>
   <p><strong><span>Educonexiones</span></strong><span> pone a disposición de los usuarios una serie de contenidos educativos en diferentes formatos (texto, audio, imagen, video) que requieren para su visualización y exploración de acceso a internet. Es responsabilidad de quien adquiere el servicio, contar con los equipos técnicos necesarios para acceder a los contenidos y garantizar que haya conectividad a Internet con las características óptimas para la visualización de estos. El usuario, en todo momento, es responsable de los costos que esto implica.</span></p>
   <li><strong>2. <span>Administración del portal</span></strong></li>
   <p><span>El diseño, arquitectura y contenidos que hacen parte del portal son propiedad de <strong>Estratégica Comunicaciones</strong>, de manera que todas las modificaciones en este (cambio de imagen, permisos de acceso, eliminación o inclusión de contenidos, entre otras posibles) quedan a discreción de la mencionada empresa y podrán ser realizadas de manera autónoma sin notificación alguna a los usuarios.</span></p>
   <li><strong>3. <span>Acceso a contenidos</span></strong></li>
   <p><span>Los contenidos descriptivos y demostrativos (prueba gratuita) del portal son de libre acceso, pero para hacer uso de las guías de aprendizaje (total o parcialmente) y los implementos de laboratorio, el usuario deberá realizar una suscripción y/o pago que está estipulado para cada servicio o producto, los cuales serán definidos por <strong>Estratégica Comunicaciones.</strong></span></p>
   <li><strong>4. <span>Derechos de uso del portal</span></strong></li>
   <p><span>Al aceptar estos términos y condiciones, el usuario de <strong>Educonexiones</strong> se compromete a que en el momento de acceder al portal, hará uso de los servicios que este ofrece de acuerdo a lo estipulado en las leyes de derechos de autor y uso de datos personales vigentes en Colombia, y en el país desde el cual ingrese. De acuerdo con lo establecido aquí, el usuario se abstiene de realizar en el portal actos con fines o efectos ilícitos, nocivos y clandestinos, que de cualquier forma puedan afectar el buen funcionamiento del portal y/o los servicios proporcionados por este. De igual manera, si el usuario conoce de intenciones o actos que podrían dañar el sistema, se compromete a notificar a <strong>Estratégica Comunicaciones</strong> y a denunciar ante las autoridades competentes. </span></p>
   <p><span>En caso de identificar un intento de daño al portal, <strong>Estratégica Comunicaciones</strong> podrá suspender los servicios al usuario inmediatamente y solo se reestablecerá cuando se haya esclarecido la situación y demuestre que está exento de responsabilidad.</span></p>
   <p><span>En todos los casos, el usuario se abstendrá de obtener, e incluso, intentar obtener, contenido o servicios del portal a través de medios o procedimientos distintos a los definidos por <strong>Estratégica Comunicaciones</strong>, razón por la que se obliga a acceder y hacer uso de estos de manera correcta y lícita. En caso contrario, <strong>Estratégica Comunicaciones</strong>podrá suspender el servicio, notificar las razones de esto y si es el caso, denunciar ante las entidades competentes para que se tomen las medidas de protección y sanción a que haya lugar. </span></p>
   <p><span>En este sentido, se específica que el usuario, por el hecho de ingresar al portal, se obliga a abstenerse de:</span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span>4.1 Utilizar el contenido con fines o efectos contrarios a las leyes de Colombia, del lugar donde reside el usuario o desde el que accede a <strong>Educonexiones.</strong> </span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span>4.2 Reproducir, copiar, imprimir, distribuir, editar, modificar y/o comercializar total o parcialmente el contenido dispuesto en <strong>Educonexiones.</strong></span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span>4.3 Suprimir, eludir o manipular los derechos de autor: marcas y registros presentes en los textos, imágenes, audios, videos y demás contenido del portal.</span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span>4.4 Publicar y enviar cualquier material y/o contenido obsceno, pornográfico, ofensivo, profano, difamatorio, etc; así como amenazas y/o acciones que violen ley.</span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span>4.5 Enviar cualquier tipo de propaganda, avisos comerciales, políticos, religiosos o de cualquier otra naturaleza.</span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span>4.6 Guardar los contenidos de <strong>Educonexiones</strong> en cualquier medio o dispositivo electrónico.</span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span>4.7 Usar el portal y sus contenidos para fines distintos a los permitidos por las disposiciones legales aplicables.</span></p>
   <p style="margin-bottom:.0001pt;text-align:justify;line-height:normal;border:none;"><span></span></p>
   <li>
      <br><strong>5. <span>Uso de la plataforma por adultos y menores de edad </span></strong></li>
   <p><span>Teniendo presente que los contenidos dispuestos en el portal son de carácter educativo y que muchos de estos están dirigidos a menores de edad, el acceso de estos se encuentra supeditado al registro en el portal de un adulto o entidad responsable (familiar, tutor, institución educativa, docente) que será el directo encargado de supervisar y garantizar el correcto uso del portal por parte de niños, niñas o joven. En conformidad con esto, el usuario y adulto responsable del menor, exime a <strong>Estratégica Comunicaciones</strong> de cualquier responsabilidad asociada con el acceso al portal, uso de los contenidos dispuestos en este o incumplimiento de las leyes vigentes en Colombia. </span></p>
   <p><span>De igual manera se advierte al usuario, que <strong>Estratégica Comunicaciones</strong> no se hará responsable por daños o afectaciones en los dispositivos tecnológicos usados mientras esté en el portar <strong>Educonexiones</strong>. Dado que esta acción se desarrolla bajo la decisión y riesgo del usuario, se entiende que es este quien debe asumir cualquier daño a su computadora, equipo, sistema o datos contenidos en los mismos.</span></p>
   <p><span>Es importante tener en cuenta que tanto la versión gratuita como la subscripción que requiere pago, tienen una vigencia de uso que depende de la extensión de los contenidos y que se especifica al momento de realizar la compra. Si el usuario no hace uso del portar, su servicios y contenidos en el tiempo estipulado, una vez vencidos los términos de la compra, no podrá acceder a estos.</span></p>
   <p><span>Para hacer seguimiento al acceso y tiempo de vigencia de los contenidos, el usuario puede acceder a su sesión, allí encontrará un reporte detallado y un calendario que le permite contabilizar los días de vigencia.</span></p>
   <li><strong>6. <span>Hipervínculos a sitios de terceros</span></strong></li>
   <p><span>En la sección “Ideas para + conexiones”, se sugieren sitios web de terceros en los que el usuario puede ampliar información sobre determinados contenidos educativos, pero queda a discreción de este acceder o no. Por lo anterior, es el usuario quien asumirá la responsabilidad y adoptará las medidas de seguridad que considere necesarias para el acceso y exploración de contenidos. </span></p>
   <p><span>Al respecto, se aclara que <strong>Estratégica Comunicaciones</strong> no tiene vínculos con ninguno de los sitios web referenciados: no respalda, patrocina, valida o tiene injerencia alguna en la publicación o eliminación de contenidos y salva responsabilidades frente a esto y su vigencia en la web.</span></p>
   <p><span>Pese a lo anteriormente expuesto, el usuario que acceda a los sitios referenciados, se obliga bajo los mismos términos dispuestos en el numeral 4 de este documento, pues los contenidos de terceros también están protegidos por las leyes de derechos de autor y propiedad intelectual. </span></p>
   
   <li><strong>7. <span style="">Derechos de autor y propiedad intelectual</span></strong></li>
   <p><span>Tanto el portal como los contenidos que hacen parte de este (imágenes, textos, audios, videos etc.), exceptuando los que se referencian en la sección “Ideas para + conexiones”, son propiedad de <strong>Estratégica Comunicaciones,</strong> y se encuentran protegidos por las leyes de propiedad intelectual y derechos de autor, razón por la que no podrán ser objeto de explotación, publicación, reproducción, distribución, modificación o cesión, por otros. En este sentido, exceptuando aquello que esté autorizado de manera explícita por <strong>Estratégica Comunicaciones</strong>, el acceso al portal no otorga a los usuarios derecho, ni titularidad alguna sobre los contenidos que alberga en el sitio.</span></p>
   <p><span>Al aceptar los términos y condiciones aquí dispuestos, usted como usuario del portal, reconoce que <strong>Estratégica Comunicaciones</strong> posee todos y cada uno de los derechos patrimoniales de todas y cada una de los contenidos del portal. </span></p>
   <li><strong>8. <span>Violación de derechos de autor y propiedad intelectual</span></strong><span>.</span></li>
   <p><span>Dado el caso en que un usuario o tercero tenga razones para considerar que algún contenido alojado en este portal es de su propiedad y que se están violando sus derechos sobre este, debe notificar formalmente a <strong>Estratégica Comunicaciones</strong> y enviar la siguiente información:</span></p>
    
   <li><span>Datos básicos de contacto: nombre completo, número de identificación, país, correo electrónico y teléfono.</span></li>
   <li><span>Indicación precisa del contenido presuntamente infringido y su ubicación en el portal.</span></li>
   <li><span>Pruebas de la autoría del contenido y presentación de los derechos de propiedad industrial y/o intelectual que posee de estos.</span></li>
   <li><span>Declaración firmada ante autoridades competencias en la que certifique que la información es veraz y que los contenidos en mención están siendo afectados por violación de derechos de propiedad intelectual y/o derechos de autor.  </span></li>
   <p><span>Dicha notificaciones deberán ser enviadas al correo electrónico <a href = "mailto: contacto@educonexiones.com"> <strong class="text-underline">  contacto@educonexiones.com </strong></a>  y en físico a la dirección: Calle 51 No.71A-18 oficina 202 Bogotá D.C.</span></p>
   <li><strong>9. <span>Alcance de los términos y condiciones de uso</span></strong></li>
   <p><span>Se sobreentiende que el usuario al acceder al portal, acepta de manera irrevocable los términos y condiciones aquí dispuestos, y que en caso de requerir arbitrar algo de lo aquí expuesto, la jurisdicción para presentar los requerimientos legales está circunscrita a los espacios estipulados por la ley en la ciudad de Bogotá – Colombia, independientemente de su domicilio presente o futuro de quien presente el requerimiento.</span><span style="font-family:Montserrat;color:#44546A;"> </span></p>
   <p style="text-align:justify;"><span></span></p>
</div>
</div>